name: Equal Experts Tech Test pipeline
on:
  push:
    branch-ignore:
      - master
      - main
jobs:
  build:
    permissions:
      contents: read
    name: Build
    runs-on: self-hosted
    services:
      registry:
        image: registry@sha256:6c5666b861f3505b116bb9aa9b25175e71210414bd010d92035ff64018f9457e
        ports:
          - 5000:5000
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: set up qemu
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a
      - name: docker-build-publish
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd
        with:
          driver-opts: network=host
      - name: Build and push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          push: true
          tags: localhost:5000/ee-tech-test/clarksoncj:v1
